### ISSUE TITLE
提供命令行接口

### ISSUE THREAD

**Issue by Shapaper** [MUedsa/BluetoothLEBatteryMonitor#7]
可以通过命令行的方式来调用程序获取电池电量吗
感激不尽！

**Comment by muedsa** [comment]
可以试试这个 https://bluetoothinstaller.com/bluetooth-command-line-tools

**Comment by Shapaper** [comment]
能简单说一下吗qwq怎样获取电量

**Comment by muedsa** [comment]
要获取什么设备的电量呢?仅BLE(蓝牙低能耗Bluetooth Low Energy)设备协议定义了通用的获取电量信息方式，经典蓝牙并没有规范的方式，不同设备获取的方式都不一样。

**Comment by Shapaper** [comment]
其实我对蓝牙不太熟悉(
我想问问咋样可以获取常规蓝牙耳机的电量吗。
![image](https://user-images.githubusercontent.com/88654772/214765196-0bb246e7-d37b-4d6b-ac27-5736401fedbd.png)

**Comment by Shapaper** [comment]
其实我对蓝牙很不熟悉
我想问问咋样可以获取到常规蓝牙耳机的电量
win10/11：
![image](https://user-images.githubusercontent.com/88654772/214765491-82aca52a-e9cc-4570-8ba9-77e84c24c863.png)

**Comment by muedsa** [comment]
常规蓝牙耳机无法通过这种方式获取电量，对于win没有方式(没有找到文档说明)获取系统这里的电量，可能需要驱动开发介入。
看这里 https://github.com/MUedsa/BluetoothLEBatteryMonitor#for-headphoneheadset

**Comment by Shapaper** [comment]
也就是说目前没有办法可以直接获取到蓝牙电量吗？
对于window系统。
会不会有歪门邪道可以实现

**Comment by muedsa** [comment]
我也不太了解是否还有其它方式。有个收费软件[https://www.bluetoothgoodies.com](https://www.bluetoothgoodies.com)，看样子可能是编写一个蓝牙驱动实现的监听。

**Comment by Shapaper** [comment]
可用的不开源
开源的不可用
😢

**Comment by muedsa** [comment]
编写驱动的成本太高了，比较复杂，我对硬件也不太了解。

**Comment by Shapaper** [comment]
确实

**Comment by Shapaper** [comment]
我觉得可能他开源了，调用的复杂度估计也很高

**Comment by muedsa** [comment]
而且驱动通常需要微软签名，这个也是收费的。

**Comment by Shapaper** [comment]
有个非常极端的办法

**Comment by Shapaper** [comment]
后台启动设置，截图，ocr提取
