### ISSUE TITLE
didn't run

### ISSUE THREAD

**Issue by ClaireCJS** [MUedsa/BluetoothLEBatteryMonitor#8]
![image](https://github.com/muedsa/BluetoothLEBatteryMonitor/assets/789591/6a524f02-49b3-4e28-8c2d-4a69c7ce9331)

**Comment by muedsa** [comment]
Due to the default settings of Windows, you could not direct  run PowerShell Script.
See  [about_Execution_Policies](https://go.microsoft.com/fwlink/?LinkID=135170)
